@LyCilph.AwesomeToDo.Web_HostAddress = http://localhost:5106

Post {{LyCilph.AwesomeToDo.Web_HostAddress}}/Projects
Content-Type: application/json

{
    "name": "Test project"
}

###

GET {{LyCilph.AwesomeToDo.Web_HostAddress}}/Projects/1
Accept: application/json

###